sudo: required
services:
  - docker
before_script:
  - docker pull atlassian/jira-software || true
script:
  - docker-compose up
# after_script:
#   - docker images

# before_deploy:
#   - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push nagesh313/test-jira-app
  on:
    branch: master
