version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - database
      - jira
      - 
    volumes:
      - ./webapp:/opt/webapp
  jira:
    image: atlassian/jira-software
    container_name: jira
    restart: always
    links:
      - database
    volumes:
      - jira-data:/var/atlassian/application-data/jira
    ports:
      - 8080:8080

  database:
    image: postgres:9.4
    container_name: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
volumes:
  jira-data:
  database-data:
