version: "2.2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      ELASTIC_PASSWORD: admin
      discovery.type: single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  log01:
    image: docker.elastic.co/logstash/logstash:7.8.0
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - log01/:/usr/share/logstash/config/
      - ./logstash.conf:/etc/logstash/conf.d

    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
volumes:
  log01:
  data01:
    driver: local
